version: 2

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unittest:
          filters:
            branches:
              ignore: master
            tags:
              only: /^v.*/
      - deploy-test-server:
          requires:
            - unittest
          filters:
            branches:
              only: develop
      - deploy-prod-server:
          requires:
            - unittest
          filters:
            branches:
              ignore: develop

jobs:
  unittest:
    docker:
      - image: python:3.6
    steps:
      - checkout

  deploy-test-server:
    docker:
      - image: python:3.6
    steps:
      - checkout

  deploy-prod-server:
    docker:
      - image: python:3.6
    steps:
      - checkout
