version: 2

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unittest
      - deploy-test-server:
          requires:
            - unittest
          filters:
            branches:
              only: develop
      - deploy-prod-server:
          requires:
            - unittest
          filters:
            branches:
              ignore: develop

jobs:
  unittest:
    steps:
      - checkout

  deploy-test-server:
    steps:
      - checkout

  deploy-prod-server:
    steps:
      - checkout
