version: 2

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unittest:
          filters:
            branches:
              ignore: master
            tags:
              only: /^v.*/
      - deploy-test-server:
          requires:
            - unittest
          filters:
            branches:
              only: develop
      - deploy-prod-server:
          requires:
            - unittest
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

jobs:
  unittest:
    docker:
      - image: python:3.6.5
    steps:
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install --no-install-recommends -y git openssh-client
      - checkout
      - run:
          name: Prepare Environment
          command: pip install pipenv --upgrade && pipenv install --dev --deploy
      - run:
          name: Run Unittest
          command: pipenv run python -m nodebin.manage py.test

  deploy-test-server:
    docker:
      - image: python:3.6.5
    steps:
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install --no-install-recommends -y git openssh-client
      - checkout
      - run:
          name: Prepare Environment
          command: pip install pipenv --upgrade && pipenv install --dev --deploy
      - run:
          name: Deploy to Test Server
          command: |
            source $(pipenv --venv)/bin/activate
            zappa deploy test || zappa update test

  deploy-prod-server:
    docker:
      - image: python:3.6.5
    steps:
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install --no-install-recommends -y git openssh-client
      - checkout
      - run:
          name: Prepare Environment
          command: pip install pipenv --upgrade && pipenv install --dev --deploy
      - run:
          name: Deploy to Prod Server
          command: pipenv shell && zappa deploy prod || zappa update prod
