version: 2

workflows:
  version: 2
  test-and-deploy:
    docker:
      - image: python:3.6
    jobs:
      - unittest
          filters:
            branches:
              ignore: master
            tags:
              only: /^v.*/
      - deploy-test-server:
          requires:
            - unittest
          filters:
            branches:
              only: develop
      - deploy-prod-server:
          requires:
            - unittest
          filters:
            branches:
              ignore: develop

jobs:
  unittest
    steps:
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install --no-install-recommends -y git openssh-client
      - checkout
      - run:
          name: Push to Git
          command: |
            mkdir -p ~/.ssh && ssh-keyscan deploy.jxltom.com >> ~/.ssh/known_hosts
            if [ -z ${CIRCLE_TAG+x} ]; then
              git push dokku@deploy.jxltom.com:flask-boilerplate "$CIRCLE_BRANCH"
            else
              exit 0
            fi

  push-to-aliyun:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Install Dependencies
          command: apt-get update && apt-get install --no-install-recommends -y git openssh-client
      - checkout
      - run:
          name: Push to Git
          command: |
            mkdir -p ~/.ssh && ssh-keyscan deploy.jxltom.com >> ~/.ssh/known_hosts
            if [ -z ${CIRCLE_TAG+x} ]; then
              git push dokku@deploy.jxltom.com:flask-boilerplate "$CIRCLE_BRANCH"
            else
              exit 0
            fi
