version: 2

workflows:
  version: 2
  test-and-deploy:
    docker:
      - image: python:3.6
    jobs:
      - unittest
          filters:
            branches:
              ignore: master
            tags:
              only: /^v.*/
      - deploy-test-server:
          requires:
            - unittest
          filters:
            branches:
              only: develop
      - deploy-prod-server:
          requires:
            - unittest
          filters:
            branches:
              ignore: develop

jobs:
  unittest
    steps:
      - checkout

  push-to-aliyun:
    steps:
      - checkout
